#!/usr/bin/env bash
# Generated by claude-jobs — edit freely, it is yours now.
# Job: {{JOB_NAME}}
#
# Flags:
#   --now       skip the random start delay (use when running by hand)
#   --dry-run   print what would run, execute nothing
set -uo pipefail

# Schedulers start with a near-empty environment: no shell profile, no PATH,
# no HOME. Everything the run needs is declared here.
export PATH={{PATH_VALUE}}
export HOME={{HOME_VALUE}}
export PYTHONIOENCODING=utf-8:replace

JOB_NAME={{JOB_NAME_Q}}
JOB_DIR={{JOB_DIR_Q}}
WORKDIR={{WORKDIR_Q}}
CLAUDE_BIN={{CLAUDE_BIN_Q}}
PROMPT_FILE="$JOB_DIR/prompt.md"
LOG={{LOG_FILE_Q}}
SUMMARY={{SUMMARY_FILE_Q}}
JITTER={{JITTER}}
LOG_MAX_BYTES={{LOG_MAX_BYTES}}
PERMISSION_MODE={{PERMISSION_MODE_Q}}
MODEL={{MODEL_Q}}
PRECHECK={{PRECHECK_Q}}
NOTIFY={{NOTIFY_Q}}

DRY_RUN=0
SKIP_DELAY=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1; SKIP_DELAY=1 ;;
    --now)     SKIP_DELAY=1 ;;
  esac
done

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG"; }

notify() {
  [ -z "$NOTIFY" ] && return 0
  CLAUDE_JOB_MESSAGE="$1" CLAUDE_JOB_NAME="$JOB_NAME" /bin/sh -c "$NOTIFY" >> "$LOG" 2>&1
}

CLAUDE_ARGS=(-p --permission-mode "$PERMISSION_MODE" --verbose --output-format stream-json)
[ -n "$MODEL" ] && CLAUDE_ARGS+=(--model "$MODEL")

if [ "$DRY_RUN" = "1" ]; then
  echo "[dry-run] job:      $JOB_NAME"
  echo "[dry-run] workdir:  $WORKDIR"
  echo "[dry-run] command:  $CLAUDE_BIN ${CLAUDE_ARGS[*]} \"\$(cat $PROMPT_FILE)\""
  [ -n "$PRECHECK" ] && echo "[dry-run] precheck: $PRECHECK"
  [ -n "$NOTIFY" ] && echo "[dry-run] notify:   $NOTIFY"
  echo "[dry-run] --- prompt ---"
  cat "$PROMPT_FILE"
  exit 0
fi

# Nothing else trims this file: the runner appends, the scheduler points
# StandardOutPath at it, and the session itself is written here in
# stream-json, so every tool call and every tool result lands verbatim.
# One generation is enough — the previous run is still there for the
# post-mortem, and two files is a bound. Set LOG_MAX_BYTES=0 to disable.
if [ "$LOG_MAX_BYTES" -gt 0 ] && [ -f "$LOG" ]; then
  # BSD wc pads its output with leading spaces, which `test -ge` rejects;
  # arithmetic expansion normalises it on both BSD and GNU.
  LOG_SIZE=$(( $(wc -c < "$LOG" 2>/dev/null || echo 0) ))
  if [ "$LOG_SIZE" -ge "$LOG_MAX_BYTES" ]; then
    mv -f "$LOG" "$LOG.1"
    log "rotated previous log (${LOG_SIZE} bytes >= ${LOG_MAX_BYTES}) to $LOG.1"
  fi
fi

# A job that fires at the same second every day is a machine rhythm. Spreading
# the start also keeps several jobs off the same usage-limit cliff.
if [ "$SKIP_DELAY" = "0" ] && [ "$JITTER" -gt 0 ]; then
  DELAY=$(( RANDOM % JITTER ))
  log "=== wake up, sleep ${DELAY}s ==="
  sleep "$DELAY"
fi

# Cheap preconditions run before spending a session, so a broken environment
# fails loudly in one second instead of halfway through the work.
if [ -n "$PRECHECK" ]; then
  if ! /bin/sh -c "$PRECHECK" >> "$LOG" 2>&1; then
    log "precheck failed, skipping this session: $PRECHECK"
    notify "$JOB_NAME: skipped, precheck failed. See $LOG."
    exit 1
  fi
fi

if [ ! -x "$CLAUDE_BIN" ] && ! command -v "$CLAUDE_BIN" >/dev/null 2>&1; then
  log "claude binary not found at $CLAUDE_BIN"
  notify "$JOB_NAME: skipped, claude binary not found at $CLAUDE_BIN."
  exit 1
fi


log "=== session start ==="
rm -f "$SUMMARY"
cd "$WORKDIR" || { log "workdir missing: $WORKDIR"; exit 1; }

# stream-json writes each step to the log as it happens instead of buffering
# until the end, which is what makes an unattended run debuggable.
"$CLAUDE_BIN" "${CLAUDE_ARGS[@]}" "$(cat "$PROMPT_FILE")" >> "$LOG" 2>&1
STATUS=$?
log "=== session end, exit=${STATUS} ==="

if [ -s "$SUMMARY" ]; then
  notify "$(cat "$SUMMARY")"
else
  notify "$JOB_NAME: session ended with exit=${STATUS} and wrote no summary. See $LOG."
fi

exit "$STATUS"
